name: CI Pipeline - Java + Docker (Docker Hub + ECR)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java app
        run: javac app/Main.java

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.chandramohan2730 }}
          password: ${{ secrets.Nezuko@30 }}

      - name: Build Docker image (tag for Docker Hub)
        run: docker build -t ${{ secrets.chandramohan2730 }}/java-ci-app:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.chandramohan2730 }}/java-ci-app:latest

      # Configure AWS credentials for ECR actions
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIA2WIKG53AVHKVQMPI }}
          aws-secret-access-key: ${{ secrets.UXeNmy40D8Y9pTBfJiO2rSAPuUY9KwybwmdaMcjK }}
          aws-region: ${{ secrets.ap-south-1 }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag image for ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=${ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/java-ci-app:latest ${ECR_URI}:latest
          echo "ECR_URI=${ECR_URI}" >> $GITHUB_OUTPUT

      - name: Push image to Amazon ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=${ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
          docker push ${ECR_URI}:latest
